### ISSUE TITLE
[버그] 엘리멘트 복사할 때 input태그 안에 있는거 한번더 복사됨

### ISSUE THREAD

**Issue by mandumeans** [busungg/HtmlBuilder#10]
엘리멘트 복사할 때 input태그 안에 있는거 한번더 복사됨

**Comment by busungg** [comment]
1. textContent, innerText등 text를 가져오는 function은 Child의 text 까지 가져오게 되어있음

2/ 자기자신의 text만을 가져오기 위해서는 Child의 정보를 삭제해야 하기 때문에 우선 Clone element를 만들어 child를 삭제한 후 text를 가져오도록 수정
