### ISSUE TITLE
[버그] 체크박스랑 라디오박스 요소 이동시 버그있음

### ISSUE THREAD

**Issue by mandumeans** [busungg/HtmlBuilder#6]
어떻게 이동되는지 안보임

**Comment by busungg** [comment]
1. CheckBox, RadioButton 은 Border Style이 적용되지 않으므로 User 가 선택을 했는지 또는 어디로 움직지는지 확인 불가능

2. Outline은 CheckBox, RadioButton 에도 해당되기 때문에 선택시에는 Outline을 사용하도록 수정

3. Outline은 Border처럼 한쪽만 적용할 수 없으므로 box-shadow를 사용하여 border-left, -right와 같이 사용하도록 수정
